queue: 'Default' #Hosted Linux Preview

steps:  
# - script: python3 -m venv venv
#   displayName: 'create VENV'
# - script: . venv/bin/activate
#   displayName: 'use VENV'
- script: pip3 install -r requirements.txt --user
  displayName: 'Install requirements'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'

- task: PythonScript@0
  inputs:
    targetType: 'filePath'
    filePath: 'manage.py'
    arguments: 'test'
