queue: 'Hosted Linux Preview'

steps:  
- script: python -m pip install --upgrade pip && pip install -r requirements.txt

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'

- task: PythonScript@0
  inputs:
    targetType: 'filePath'
    filePath: 'manage.py'
    arguments: 'test'
