queue: 'Default' #HHosted Linux Preview

steps:  
- script: apt-get install python-pip
  displayName: 'Install PIP'
- script: pip install -r requirements.txt
  displayName: 'Install requirements'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'

- task: PythonScript@0
  inputs:
    targetType: 'filePath'
    filePath: 'manage.py'
    arguments: 'test'
