queue: 'Default' #Hosted Linux Preview

steps:  
- script: pip3 install -r requirements.txt
  displayName: 'Install requirements'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'

- task: PythonScript@0
  inputs:
    targetType: 'filePath'
    filePath: 'manage.py'
    arguments: 'test'
